name: Deploy syntethics-app to build-demo


on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v6

      - name: Build synthetics script
        working-directory: synthetics-app
        run: npm run build

      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v5
        with:
          role-to-assume: ${{ secrets.SYNTHETICS_APP_GH_ROLE_ARN }}
          aws-region: eu-west-2

      - name: SAM build and test
        working-directory: synthetics-app
        run: sam build

      - name: Deploy SAM app
        uses: govuk-one-login/devplatform-upload-action@v3.11.0
        with:
          artifact-bucket-name: ${{ secrets.SYNTHETICS_APP_ARTIFACT_BUCKET_NAME }}
          signing-profile-name: ${{ secrets.SIGNING_PROFILE_NAME }}
          template-file: ./synthetics-app/.aws-sam/build/template.yaml
          synthetics-directory: ./synthetics-app
